import React,{useEffect,useState}from'react';
import{createRoot}from'react-dom/client';
import{createPortal}from'react-dom';
import{AnimatePresence,motion}from'framer-motion';
import{ArrowLeft,ArrowRight,Award,Check,ChevronDown,Menu,Target,Volume2,VolumeX,X}from'lucide-react';
import{useLessonAudio}from'../../shared/useLessonAudio';
import'./styles.css';
import hookArt from'./assets/illustrations/judges-mismatched-rubrics.png';
import sharedArt from'./assets/illustrations/judges-shared-rubric.png';
import rulesArt from'./assets/illustrations/upfront-rulebook.png';
import warningArt from'./assets/illustrations/measurement-method-warning.png';
import controlArt from'./assets/illustrations/control-accounts.png';
import unitsArt from'./assets/illustrations/units-of-measure.png';
import precisionArt from'./assets/illustrations/level-of-precision.png';
import evmArt from'./assets/illustrations/evm-measurement-rules.png';
import decisionsModalArt from'./assets/illustrations/modal-four-decisions.png';
import measurementModalArt from'./assets/illustrations/modal-measurement-risk.png';
import examModalArt from'./assets/illustrations/modal-exam-lens.png';

const tabs=['The judging problem','What it means','Four decisions','Why plan it','Exam lens'];
const panels=[
 ['Control Accounts',"The point in the WBS where scope, budget, and schedule are integrated and measured together — usually above the individual work-package level, but below the overall project. It's the level at which cost performance actually gets reported and managed, rather than tracking every single work package individually and drowning the project manager in noise.","Example: On a construction project, “Foundation Work” might be a control account encompassing excavation, rebar, and concrete pour — performance gets measured at the “Foundation Work” level, not chased separately for each individual work package.",controlArt],
 ['Units of Measure','An agreed unit — currency, staff-hours, or some combination — so that every cost report speaks the same language. A plan that tracks some costs in dollars and others in labor-hours without a clear conversion rule produces numbers nobody can honestly compare.','Example: A multi-country project might standardize on staff-hours for labor cost tracking specifically to neutralize currency fluctuation between regions, converting to a reporting currency only at the point of consolidated reporting.',unitsArt],
 ['Level of Precision','How exact cost figures need to be — rounded to the nearest thousand, or tracked to the cent. Too much precision on early estimates creates a false sense of accuracy the estimate hasn’t earned. Too little precision late in the project hides real variance that needs attention.','Example: A project might agree that early-phase estimates get rounded to the nearest $1,000, while actuals recorded during execution get tracked to the dollar — an explicit rule that keeps the two from being confused with each other.',precisionArt],
 ['EVM Measurement Rules','Agreeing in advance on how percent-complete gets calculated for in-progress work, which baseline values (PV, EV, AC) get updated on what cadence, and which specific EVM formulas — CPI, SPI, EAC — the project will report on a recurring basis.',"Example: If one control account owner reports percent-complete based on time elapsed and another reports based on actual deliverable completion, the resulting Earned Value figure is meaningless — “earned” means something different depending on who's reporting it.",evmArt]
];
const reveals={
 hook:{image:sharedArt,title:'Cost tracking on a project works exactly the same way.',text:"The third enabler of ECO Process Task 6 asks the project manager to plan spend tracking throughout the project life cycle — establishing, upfront, the control accounts, units of measure, level of precision, and Earned Value Management rules that will govern how spend gets monitored from the first dollar to the last. This is part of PMBOK® 8's Plan Financial Management thinking — and the key point is timing. These rules aren't decided partway through the project once someone notices the tracking is inconsistent. They're set in advance, precisely so that every cost report produced afterward means the same thing to everyone reading it."},
 meaning:{image:decisionsModalArt,title:'Four decisions anchor a workable spend-tracking plan.',text:'Four decisions anchor a workable spend-tracking plan: control accounts, units of measure, level of precision, and EVM measurement rules. Get these decisions made upfront, and every cost report speaks the same language from the first dollar spent to the last. Leave them unplanned, and even the most diligent tracking produces numbers nobody can actually trust to compare.'},
 warning:{image:measurementModalArt,title:'The yardstick cannot move halfway through.',text:"EVM and cost variance analysis are only meaningful when every reporting period uses the same rules as the last one. A CPI of 0.85 this month is only informative if it's calculated the same way CPI was calculated last month. Change the measurement rules mid-project without documenting it, and a genuine performance improvement can look identical to a change in how the number was calculated — leaving the project manager unable to tell whether the project actually got better, or whether the yardstick just moved."},
 exam:{image:examModalArt,title:'The shared rubric is agreed before anyone starts scoring.',text:"Planning spend tracking means deciding, before a dollar is spent, exactly how cost performance will be measured and reported for the rest of the project's life. Control accounts define where cost gets tracked. Units of measure and level of precision define how it gets expressed. And EVM measurement rules define how “on track” or “over budget” actually gets calculated — consistently, reporting period after reporting period. Get these decisions made upfront, and every cost report from month one to project close speaks the same language. Leave them unplanned, and even the most diligent tracking produces numbers nobody can actually trust to compare.",bullets:['Four upfront decisions: control accounts (where), units of measure and precision (how expressed), EVM rules (how “on track” is calculated)','Rules are set before execution starts — not improvised once inconsistent tracking is already noticed','Consistency across reporting periods is what makes CPI/SPI/EAC trustworthy — an undocumented rule change can masquerade as real performance change','A missing units-of-measure decision (e.g., currency vs. local currency) breaks comparability even when each control account is individually diligent']}
};
const quizzes={
 units:{question:"Scenario: Three months into a project, the finance lead notices that one control account has been reporting cost performance in local currency, while another has been reporting in the project's standard reporting currency — with no documented conversion rule between them. What does this situation best illustrate?",answers:['A normal and acceptable difference in reporting style between control accounts','Evidence that Earned Value Management doesn’t work across multi-currency projects','Spend-tracking rules failed to define consistent units of measure','A sign that control accounts were defined at too granular a level'],correct:2,good:'Correct! Agreeing on units of measure upfront is exactly what prevents this. Without that decision made in advance, control accounts end up reporting in ways that can’t be reliably compared or rolled up into one consolidated view of project cost performance.',bad:'Reconsider — this isn’t stylistic variation, an EVM limitation, or a granularity problem. It’s a missing measurement rule that should have been agreed before execution began.'},
 method:{question:'Scenario: Midway through a project, the team quietly switches from calculating percent-complete based on deliverable acceptance to calculating it based on time elapsed — without documenting the change. The next reporting period shows a sudden CPI improvement. What is the most likely explanation?',answers:['The project genuinely improved its cost performance','The CPI shift may reflect the undocumented measurement change, not real performance','CPI cannot be affected by how percent-complete is calculated','The team should immediately report this improvement to the sponsor as a success'],correct:1,good:'Right — this is precisely the trap: an undocumented change in how percent-complete is calculated can produce a CPI shift that looks identical to genuine improvement, making it impossible to tell which one actually happened.',bad:'Reconsider — a change in measurement method partway through, done without documentation, is exactly the scenario this lesson warns can be mistaken for real performance change.'}
};

function Modal({data,close,done}){const[step,setStep]=useState(0);useEffect(()=>{const f=e=>e.key==='Escape'&&close();addEventListener('keydown',f);return()=>removeEventListener('keydown',f)},[close]);const hasMemoryStep=Boolean(data.bullets?.length);return createPortal(<motion.div className="modal-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={close}><motion.section className="focus-modal" initial={{y:24,opacity:0,scale:.98}} animate={{y:0,opacity:1,scale:1}} exit={{y:12,opacity:0}} onClick={e=>e.stopPropagation()}><button className="modal-x" aria-label="Close" onClick={close}><X/></button><AnimatePresence mode="wait">{step===0?<motion.div key="content" initial={{opacity:0,x:-12}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-12}}><img className="modal-illustration" src={data.image} alt=""/><h3>{data.title}</h3><div className="modal-copy"><p>{data.text}</p></div></motion.div>:<motion.div className="memory-step" key="memory" initial={{opacity:0,x:18}} animate={{opacity:1,x:0}} exit={{opacity:0,x:18}}><p className="eyebrow">THINGS TO REMEMBER</p><h3>Exam-relevant enablers</h3><ul>{data.bullets.map(x=><li key={x}>{x}</li>)}</ul></motion.div>}</AnimatePresence>{hasMemoryStep&&step===0?<button className="modal-action" onClick={()=>setStep(1)}>Next <ArrowRight/></button>:<button className="modal-action" onClick={()=>{done();close()}}>Mark as read <Check/></button>}</motion.section></motion.div>,document.body)}
function Quiz({data,finish}){const[p,setP]=useState(null);return createPortal(<div className="knowledge-backdrop"><motion.section className="knowledge-modal" initial={{y:20,opacity:0}} animate={{y:0,opacity:1}}><p className="quiz-label"><Target/> MICRO KNOWLEDGE CHECK</p><h3>{data.question}</h3><div className="answers">{data.answers.map((a,i)=><button key={a} className={p===i?(i===data.correct?'correct':'wrong'):''} onClick={()=>setP(i)}><span>{String.fromCharCode(65+i)}</span>{a}</button>)}</div>{p!==null&&<><p className={`feedback ${p===data.correct?'good':'bad'}`}>{p===data.correct?data.good:data.bad}</p><button className="finish-check" onClick={finish}>Finish check <ArrowRight/></button></>}</motion.section></div>,document.body)}
function App(){const[s,setS]=useState(0),[done,setDone]=useState(Array(5).fill(false)),[modal,setModal]=useState(null),[quiz,setQuiz]=useState(null),[sound,setSound]=useState(true),[outline,setOutline]=useState(false),[open,setOpen]=useState(0),[read,setRead]=useState([true,false,false,false]),[warningRead,setWarningRead]=useState(false);useLessonAudio(sound);const mark=i=>setDone(d=>d.map((x,j)=>j===(i??s)?true:x));const go=i=>{if(i>=0&&i<5&&(i<=s+1||done[i-1])){setOpen(0);setS(i)}};const finishReveal=()=>{if(modal==='warning')setWarningRead(true);else mark()};const finishQuiz=()=>{setQuiz(null);mark()};let c;
if(s===0)c=<div className="hero-layout"><div><p className="eyebrow">LESSON 4.4.3 · PLAN SPEND TRACKING THROUGHOUT THE PROJECT LIFE CYCLE</p><h1>Every score must use <span>the same rubric.</span></h1><p className="lead">Imagine judges scoring an Olympic gymnastics final, each using a slightly different personal rubric they never agreed on beforehand — one weighting difficulty heavily, another weighting execution. Every score is internally consistent for that judge, but the moment you compare scores across judges, or across events, the numbers mean completely different things depending on who produced them.</p><button className="primary-cta" disabled={done[0]} onClick={()=>setModal('hook')}>{done[0]?'Shared rubric revealed':'Reveal the shared rubric'} <ArrowRight/></button></div><img className="lesson-art" src={hookArt} alt="Gymnastics judges using mismatched scoring rubrics"/></div>;
if(s===1)c=<div className="hero-layout compact-hero"><div><p className="eyebrow">WHAT THIS ENABLER MEANS</p><h2>This isn’t a bookkeeping detail to settle later.</h2><p className="lead">It’s the agreement that makes every cost report from month one to project close actually mean the same thing.</p><button className="primary-cta" disabled={done[1]} onClick={()=>setModal('meaning')}>{done[1]?'Spend-tracking plan revealed':'Reveal the four decisions'} <ArrowRight/></button></div><img className="lesson-art" src={rulesArt} alt="Team unlocking measurement rules before the project timeline begins"/></div>;
if(s===2)c=<div className="wide-page"><p className="eyebrow">FOUR DECISIONS TO MAKE UPFRONT</p><h2>Four specific decisions anchor a workable spend-tracking plan.</h2><p className="lead">Click each to explore.</p><div className="accordion">{panels.map((p,i)=><div className={`accordion-item ${open===i?'open':''}`} key={p[0]}><button onClick={()=>{setOpen(open===i?null:i);setRead(r=>r.map((x,j)=>j===i?true:x))}}><span className="category-number">0{i+1}</span><strong>{p[0]}</strong><ChevronDown/></button><AnimatePresence>{open===i&&<motion.div className="accordion-copy illustrated-accordion" initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:0}}><img className="accordion-art" src={p[3]} alt=""/><div><p>{p[1]}</p><p className="accordion-example"><em>{p[2]}</em></p></div></motion.div>}</AnimatePresence></div>)}</div>{read.every(Boolean)&&!done[2]&&<button className="knowledge-cta" onClick={()=>setQuiz('units')}><Target/> Start knowledge check <ArrowRight/></button>}</div>;
if(s===3)c=<div className="hero-layout"><div><p className="eyebrow">WHY THIS MUST BE PLANNED, NOT IMPROVISED</p><h2>Don’t change the yardstick halfway through.</h2><p className="lead">Here’s the reason this can’t be worked out on the fly once spend data starts coming in — and it’s the same reason a judge can’t change their scoring rubric halfway through the competition.</p>{!warningRead?<button className="primary-cta" onClick={()=>setModal('warning')}>Reveal the measurement risk <ArrowRight/></button>:!done[3]?<button className="knowledge-cta" onClick={()=>setQuiz('method')}><Target/> Start knowledge check <ArrowRight/></button>:null}</div><img className="lesson-art" src={warningArt} alt="Two identical cost trends produced by different measurement conditions"/></div>;
if(s===4)c=<div className="exam-layout"><div className="exam-visual"><img src={sharedArt} alt="Judges using one shared scoring standard"/></div><div><p className="eyebrow">SYNTHESIS (EXAM LENS)</p><h2>The rubric is agreed before anyone starts scoring.</h2><p className="lead">Back to the judges’ panel one more time — because the whole point of a shared rubric is that it’s agreed before anyone starts scoring, not adjusted once the scores are already in.</p><button className="primary-cta" disabled={done[4]} onClick={()=>setModal('exam')}>{done[4]?'Exam lens reviewed':'Reveal the exam lens'} <ArrowRight/></button></div></div>;
const ready=done[s];return <div className="app-shell"><header className="topbar"><button className="course-select"><Award/><span>PMP Project Management Professional</span><ChevronDown/></button><div className="module-progress"><div>{Array.from({length:10},(_,i)=><span className={`progress-dot ${i<8?'done':i===8?'active':''}`} key={i}>{i<8?<Check size={10}/>:<span/>}</span>)}</div></div><div className="top-actions"><button className="ghost-button" onClick={()=>setSound(v=>!v)}>{sound?<Volume2/>:<VolumeX/>}<span>{sound?'Sound on':'Sound off'}</span></button><button className="ghost-button"><X/><span>Quit</span></button></div></header><main className="workspace"><section className="lesson-stage"><div className="outline"><button className="menu-button" onClick={()=>setOutline(!outline)}><Menu/></button>{outline&&<div className="outline-panel"><div className="outline-summary"><strong>Lesson 4.4.3</strong></div><div className="lesson-list">{tabs.map((x,i)=><button className={`lesson ${s===i?'current':''}`} key={x} onClick={()=>go(i)}><span>{i+1}</span><span>{x}</span>{done[i]&&<Check/>}</button>)}</div></div>}</div><article className="lesson-card"><div className="section-tabs"><p>SECTION {s+1} OF 5</p><div>{tabs.map((x,i)=><button className={`${done[i]?'done':''} ${s===i?'active':''}`} key={x} onClick={()=>go(i)}>{done[i]&&<Check/>}{x}</button>)}</div></div><div className="lesson-content">{c}</div>{ready&&<p className="completion"><Check/> Interaction complete — continue when ready.</p>}<footer className="nav-footer"><button className="secondary-button" disabled={!s} onClick={()=>go(s-1)}><ArrowLeft/> Previous</button><button className={`primary-button ${ready?'unlocked':''}`} disabled={!ready} onClick={()=>s<4&&go(s+1)}>{s===4?'Continue to next lesson':'Continue'} <ArrowRight/></button></footer></article></section></main><AnimatePresence>{modal&&<Modal data={reveals[modal]} close={()=>setModal(null)} done={finishReveal}/>}</AnimatePresence>{quiz&&<Quiz data={quizzes[quiz]} finish={finishQuiz}/>}</div>}
createRoot(document.getElementById('root')).render(<App/>);
